version: '3.4'

volumes:
  db:

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  app:
    image: 'detector:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/detector
      - SPRING_DATASOURCE_USERNAME=detector
      - SPRING_DATASOURCE_PASSWORD=detector