server:
  port: 4675
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/detector?reWriteBatchedInserts=true
    username: detector
    password: detector
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc:
          batch_size: 5
      order_inserts: true
  flyway:
    locations: classpath:flyway/migrations
    enabled: true
    user: detector
    password: detector
    url: jdbc:postgresql://localhost:5432/detector
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core: INFO
#      hibernate:
#        SQL: INFO
#        type:
#          descriptor:
#            sql:
#              BasicBinder: INFO